packaging_format = 2

id = "froxlor"
name = "Froxlor"
description.en = "server administration software for your needs"
description.fr = "server administration software for your needs"

version = "2.0.19~ynh1"

maintainers = ["eric_G"]

[upstream]
license = "GPL-2.0"
website = "www.froxlor.org"
code = "https://github.com/Froxlor/Froxlor/"

[integration]
yunohost = ">= 11.1.18"
architectures = "all"
multi_instance = true
ldap = false
sso = false
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

    [resources.sources]

        [resources.sources.main]
        url = "https://github.com/Froxlor/Froxlor/releases/download/2.0.19/froxlor-2.0.19.tar.gz"
        sha256 = "b0ba7a3d0fe1e3e6f26f636e43411e22eea1f613f666ef593cbc58e7ecf6d936"
        autoupdate.strategy = "latest_github_tag"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]

    [resources.apt]
    packages = "mariadb-server, php8.1-mysql"

    [resources.database]
    type = "mysql"
